#ifndef PROPERTIES_H
#define PROPERTIES_H

enum Color { RED, GREEN, BLUE, COLOR_LENGTH }; 
enum Content { CONTENT0, CONTENT1, CONTENT2, CONTENT3, CONTENT_LENGTH }; 
enum Weight { HEAVY, MEDIUM, LIGHT, WEIGHT_LENGTH }; 
enum None {NA, NONE_LENGTH }; 

#endif 
