
#ifndef UTILITIES_H
#define UTILITIES_H

#define GRASP_SUCCESS_RATE (0.95)
#define DROP_SUCCESS_RATE (0.95)
#define SUCCESS_REWARD (100.0)
#define FAILURE_PENALTY (-100.0)
#define DISCOUNT_FACTOR (0.99)
#define TINY_DELTA (0.000001)

#endif 
